sudo: false

language: go

git:
  depth: 1

install: go get -v github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: yimeng/yimeng.github.com
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
after_deploy:
  - curl -s  --form-string "token=$APP_TOKEN"  --form-string "user=$USER_KEY"  --form-string "message=hello world"  https://api.pushover.net/1/messages.json

